tools: pass on konflux bot commits
Konflux bot started filing chore PRs and they are failing because of:
```
error: invalid commit: DCO signoff malformed: "Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>" does not contain expected "Signed-off-by: red-hat-konflux[bot] <126015336+red-hat-konflux[bot]@users.noreply.github.com>"
```

Fix the function to pass on commits authored by the bot.

Signed-off-by: Shereen Haj <shajmakh@redhat.com>