deps: bump `x/net` to fix GO-2026-5026
govulncheck caught a CVE being called by a dependency:
```
Vulnerability #1: GO-2026-5026
    Invoking failure to reject ASCII-only Punycode-encoded labels in
    golang.org/x/net/idna
  More info: https://pkg.go.dev/vuln/GO-2026-5026
  Module: golang.org/x/net
    Found in: golang.org/x/net@v0.53.0
    Fixed in: golang.org/x/net@v0.55.0
    Example traces found:
Error:       #1: internal/remoteexec/command.go:101:33: remoteexec.PortForwardToPodByNames calls spdy.dialer.Dial, which eventually calls idna.ToASCII
```

bump the module to the fixed version as suggested.

Signed-off-by: Shereen Haj <shajmakh@redhat.com>